### ISSUE TITLE
Enable creating `AuthorizationPolicies` that bind to a workload not a Service (as in an L4 policy)

### ISSUE THREAD

**Issue by ca-scribner** [canonical/istio-beacon-k8s-operator#76]
### Enhancement Proposal

# Issue

For every workload that istio-beacon's `Waypoint` serves, istio automatically creates a ztunnel-bound (L4) policy allowing `Waypoint`->`Workload`, which has the side effect of blocking any other traffic that goes directly to the Workloads (unless there are other L4 policies in place).  We then provide, through the `ServiceMeshConsumer` lib, a way for applications to request `AuthorizationPolicies` to allow traffic to a workload.  An example is:

```
self._mesh = ServiceMeshConsumer(
    self,
    policies=[
        Policy(
            relation="metrics",
#             service="some-service",  # Optional - defaults to the related app's default juju service
            endpoints=[
                Endpoint(
                    hosts=[self._my_host_name],
                    ports=[HTTP_LISTEN_PORT],
                    methods=["GET"],
                    paths=["/metrics"],
                ),
            ],
        ),
        Policy(
            relation="data",
            endpoint=[
                Endpoint(
                    hosts=[self._my_host_name],
                    ports[HTTP_LISTEN_PORT],
                    methods=["GET"]
                    paths=["/data"],
                ),
            ],
        ),
    ],
)
```

This application requests from beacon the generation of `AuthorizationPolicies` described by the above `Policy` objects.  These `AuthorizationPolicies` are **bound to a `Waypoint` and target a `Service`** (eg: they're "L7 policies" applied at the `Waypoint`).    As most networking in Kubernetes travels through a Service, this is usually the behaviour we want.

For prometheus(/grafana-agent/mimir), metrics collection is a pull action where prometheus scrapes the metrics endpoint **for each workload pod directly, bypassing the Service/Waypoint** (eg: prometheus does `curl POD_IP` rather than `curl SERVICE_URL`).  This is done because, if accessed through the service, Prometheus would get round-robined across the pods rather than hit each one deterministically.  In how we've currently modeled this, however, there's no way to enable this communication.  

# Solution

In general, to allow prometheus this direct-to-workload access we must create ztunnel-bound (L4) policies for this traffic.  This was confirmed by the upstream istio community [in this slack conversation](https://istio.slack.com/archives/C041EQL1XMY/p1748633158707859).  How we model/implement that in Juju needs to be figured out...

### Add a field to `Policy`

We could add a field to the `Policy` object that decides whether this is a L4 or L7 policy, such as:

```python
self._mesh = ServiceMeshConsumer(
    self,
    policies=[
        Policy(
            bind_to="Service"  # /"Workload" <-- NEW FIELD
            relation="metrics",
#             service="some-service",  # Optional - defaults to the related app's default juju service
            endpoints=[
                Endpoint(
                    hosts=[self._my_host_name],
                    ports=[HTTP_LISTEN_PORT],
                    methods=["GET"],
                    paths=["/metrics"],
                ),
            ],
        ),
      ],
    )
```

I haven't thought through the naming or what other objects could be modelled here, so there's still work to do.  

#### Open questions
* to bind to a workload, we need the label selector of those workloads.  How do we get that?  We could infer it based on how juju works (Juju always creates services with selector `app.kubernetes.io/name=APPLICATION_NAME`), or if we know the `Service` object we could just copy its label selector

### Add a new `PolicyL4` object

Similar to above, but instead of having a field in `Policy` we could have separate L4 and L7 Policy objects

### Create another charm for operating ztunnel-bound policies (a sort of istio-beacon-for-l4)

Haven't thought this through much.  This at least makes it clear who acts on a ztunnel-bound policy vs waypoint-bound policy, but I don't think it makes it easier for a charm dev that needs to put their application on a service mesh

# Other important information
* #75 implements "create AuthorizationPolicy" logic for things related directly to beacon.  That logic suffers from the same bug described here.  When we fix this issue, we need to either fix the broken parts of #75 as well or open up a separate issue to capture that

**Comment by ca-scribner** [comment]
I cite prometheus/mimir/grafana-agent as the straw man example here.  There's probably other applications that behave this way too, but I can't think of any atm.

**Comment by adhityaravi** [comment]
I was trying to add service mesh support to alertmanager and came across a behavior that was contradicting this. TLDR: prometheus was able to successfully scrape the metrics enpoint from alertmanager.

Steps to reproduce:

- Pull the [alertmanager code](https://github.com/canonical/alertmanager-k8s-operator/tree/feature/service-mesh-support) that includes service mesh support
```sh
git clone --branch features/service-mesh-support https://github.com/canonical/alertmanager-k8s-operator.git
```

- Pack the charm
```sh
charmcraft pack
```

- Deploy the stack
```sh 
# deploy istio core
juju add-model istio-system
juju deploy istio-k8s --trust --channel=latest/edge

# deploy alertmanager and friends
juju add-model dev
juju deploy istio-beacon-k8s --trust --channel=latest/edge
juju deploy istio-beacon-k8s --trust --channel=latest/edge
juju deploy prometheus-k8s --trust
juju deploy ./alertmanager-k8s_ubuntu@24.04-amd64.charm --trust --resource alertmanager-image=ubuntu/alertmanager:0-22.04

# wait for idle

# enable model on mesh
juju config istio-beacon-k8s model-on-mesh=true

# add alertmanager relations
 juju integrate alertmanager-k8s:ingress istio-ingress-k8s:ingress-unauthenticated
juju integrate alertmanager-k8s istio-beacon-k8s
juju integrate alertmanager-k8s:self-metrics-endpoint prometheus-k8s:metrics-endpoint

# expose prometheus-k8s ui
kubectl port-forward --address=0.0.0.0 svc/prometheus-k8s 9090:9090 -n dev 
```

- Access the Prometheus UI and check the status of the alertmanager metrics provider

PS:
Even after removing the auth policies added to allow metrics endpoint access to alertmanager, prometheus is able to contact alertmanager.

**Comment by ca-scribner** [comment]
I deployed @adhityaravi's repro case and watched the ztunnel and waypoint logs.  What I see is that:
1. from an off-mesh pod (deployed with `kubectl -n off-mesh run curl --rm -i --tty --image radial/busyboxplus:curl -- sh`:
  a. `curl http://alertmanager-k8s-0.alertmanager-k8s-endpoints.dev.svc.cluster.local:9093/metrics`: rejected by ztunel 
    * ztunnel logs: `error="connection closed due to policy rejection: allow policies exist, but none allowed"`
    * waypoint logs: nothing
  b. `curl ALERTMANAGER_IP:9093/metrics`: rejected by ztunel
    * ztunnel logs: `error="connection closed due to policy rejection: allow policies exist, but none allowed"`
    * waypoint logs: nothing
2. prometheus pod (`juju ssh prometheus-k8s bash`): 
  a. `curl http://alertmanager-k8s-0.alertmanager-k8s-endpoints.dev.svc.cluster.local:9093/metrics`: works 
    * ztunnel logs: I see logs for "outbound" traffic, but nothing inbound: 
      * `2025-06-02T18:04:25.590473Z	info	access	connection complete	src.addr=10.1.253.214:59550 src.workload="prometheus-k8s-0" src.namespace="dev" src.identity="spiffe://cluster.local/ns/dev/sa/prometheus-k8s" dst.addr=10.1.253.208:15008 dst.hbone_addr=10.1.253.212:9093 dst.workload="istio-beacon-k8s-dev-waypoint-69876f5b6c-ts45n" dst.namespace="dev" dst.identity="spiffe://cluster.local/ns/dev/sa/istio-beacon-k8s-dev-waypoint" direction="outbound" bytes_sent=143 bytes_recv=35248 duration="18ms""`
    * waypoint logs: shows traffic, but no denial

   b. `curl ALERTMANAGER_IP:9093/metrics`: works
    * ztunnel logs: *identify* to curling the headless service above (outbound traffic, no denial)
      * `2025-06-02T18:06:03.012187Z	info	access	connection complete	src.addr=10.1.253.214:39188 src.workload="prometheus-k8s-0" src.namespace="dev" src.identity="spiffe://cluster.local/ns/dev/sa/prometheus-k8s" dst.addr=10.1.253.208:15008 dst.hbone_addr=10.1.253.212:9093 dst.workload="istio-beacon-k8s-dev-waypoint-69876f5b6c-ts45n" dst.namespace="dev" dst.identity="spiffe://cluster.local/ns/dev/sa/istio-beacon-k8s-dev-waypoint" direction="outbound" bytes_sent=88 bytes_recv=35255 duration="6ms"`
    * waypoint logs: shows traffic, no denial

In both 2.a and 2.b the waypoint is capturing the traffic going directly to the Pod.  This is because we set [`istio.io/waypoint-for=all`](https://istio.io/latest/docs/ambient/usage/waypoint/#waypoint-traffic-types) on our waypoint labels, meaning that the waypoint will capture both traffic destined for a service and a pod.  

**TODO: where do I bind a policy for controlling this traffic going to the pod?  to the waypoint?  how do i confine it to JUST that pod's traffic?**

If I change the Waypoint gateway's labels from [`istio.io/waypoint-for=all` to `istio.io/waypoint-for=service`](https://istio.io/latest/docs/ambient/usage/waypoint/#waypoint-traffic-types), then I see both 2.a and 2.b rejected at ztunnel with 401 errors and no traffic going through the waypoint.  

So in @adhityaravi's case, his traffic is flowing through the waypoint to the alertmanager pods and that's why it is not being rejected.  

If I [upgrade istio to 1.26.1](https://github.com/canonical/istio-k8s-operator/pull/68) and create this authorization policy which adds an allow-nothing policy to all waypoints by default:
```
apiVersion: security.istio.io/v1
kind: AuthorizationPolicy
metadata:
 name: allow-nothing-for-waypoints
 namespace: istio-system # important that it is in root namespace
spec:
  targetRefs:
    - kind: GatewayClass
      group: gateway.networking.k8s.io
      name: istio-waypoint
```
then what I see is traffic in 2.a and 2.b is **denied** at the waypoint (`[2025-06-02T18:43:37.317Z] "GET /metrics HTTP/1.1" 403 - rbac_access_denied_matched_policy[none] - "-" 0 19 0 - "-" "curl/7.68.0" "2b3efa0f-55a2-4400-a407-ec6a82cf673d" "10.1.253.212:9093" "-" encap - 10.1.253.212:9093 10.1.253.214:60528 - default`).  So I think then what @adhityaravi is seeing is:
* traffic going directly to the pod was being captured by the waypoint (unlike what I thought initially) because `waypoint-for=all`
* traffic through the waypoint to the alertmanager pod **was not restricted by any AuthorizationPolicy**, and this is why it succeeded.  

And if we add an allow-nothing policy bound to the waypoint, now the prometheus->am traffic is blocked, so the policy that @adhityaravi is not successfully allowing the traffic through (I think because its not correctly targeting the pod).

**TODO: Why did I hit something different with prometheus/beacon?**

So then the next question is, if we're using `waypoint-for=all` to capture Pod traffic, how do we create AuthorizationPolicies to restrict that traffic?  Specifically:
1. where do we bind the policy to?
2. what/how do we target the policy to (eg: how do we make a policy that applies to traffic to a single pod)?

I think (1) is easy - we bind to the waypoint.  But I'm not sure about (2)... Testing this, I created:

```yaml
apiVersion: security.istio.io/v1
kind: AuthorizationPolicy
metadata:
  labels:
    app.juju.is/created-by: istio-beacon-k8s
    app.kubernetes.io/instance: istio-beacon-k8s-dev
    kubernetes-resource-handler-scope: istio-authorization-policy
  name: allow-prometheus-to-alertmanager-pod-via-waypoint
  namespace: dev
spec:
  rules:
  - from:
    - source:
        principals:
        - cluster.local/ns/dev/sa/prometheus-k8s
    to:
    - operation:
        # NOTE: No "host" here
        methods:
        - GET
        paths:
        - /metrics
        ports:
        - "9093"
  targetRefs:
  - group: gateway.networking.k8s.io
    kind: Gateway
    name: istio-beacon-k8s-dev-waypoint

```

This binds a policy to the waypoint and successfully allows prometheus to scrape alertmanager pods (I see `curl ALERTMANAGER_POD:9093/metrics` succeeding).  But regarding point (2) above, this policy targets **everything** through the waypoint, not just traffic to alertmanager, so it allows prometheus to scrape **everyone** at `:9093/metrics`.  We can demonstrate that by deploying something else that responds on `:9093/metrics`:

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: echoserver
  namespace: dev
spec:
  replicas: 5
  selector:
    matchLabels:
      app: echoserver
  template:
    metadata:
      labels:
        app: echoserver
    spec:
      containers:
      - image: ealen/echo-server:latest
        imagePullPolicy: IfNotPresent
        name: echoserver
        ports:
        - containerPort: 9093
        env:
        - name: PORT
          value: "9093"
```

From the prometheus pod if we `curl ECHOSERVER_IP:9093/metrics` we see it succeed (and just to ensure its not a false positive, we can see `curl ECHOSERVER_IP:9093/not-metrics` fails).

I tried accomplishing (2) by defining `hosts` in the AuthorizationPolicy, but that doesn't work either since you can scrape a pod without actually defining a host header.
